name: Create Storage + Upload Images
on: [workflow_dispatch]
jobs:
  create-storage-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: bash scripts/upload_images.sh
