name: Output Front Door Endpoints
on: [workflow_dispatch]
jobs:
  output-endpoints:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az network front-door show --name ntms-frontdoor --resource-group your-rg --query "frontendEndpoints[].hostName" --output tsv
